### ISSUE TITLE
error thrown when using is_na and is_not_na operators

### ISSUE THREAD

**Issue by harveyl888** [harveyl888/queryBuilder#1]
Error: argument is of length zero is thrown when using the is_na or is_not_na operators on filters.

**Comment by eaurele** [comment]
Though it seems it can be safely ignored, there remains a JavaScript error: `Uncaught Error: Unknown SQL operation for operator "is_not_na"`.  

From example app 01:  
![capture_2018-12-12-1502](https://user-images.githubusercontent.com/10000823/49874592-2e5ba780-fe1f-11e8-9a49-a64e26a40b8d.PNG)
